### ISSUE TITLE
Change default value of SSLCARevocationCheck to chain for better security?

### ISSUE THREAD

**Issue by ghost** [mprahl/s2i-angular-httpd24#1]
In your configuration file, I notice that you do not change the default value of **SSLCARevocationCheck**, which is **none** and disable the certificate revocation list (CRL) checking.  

The Http server [official document](https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslcarevocationcheck) recommends to set **SSLCARevocationCheck** to **chain**, for better security. "When set to **chain (recommended setting)**, CRL checks are applied to all certificates in the chain". 

 I wonder if there is any security concern if SSLCARevocationCheck is set to none. Thanks.

**Comment by mprahl** [comment]
@HCHCHH I appreciate the security concern, but the `SSLCARevocationCheck` option is only useful when validating certificates presented to the Apache web server when it is performing client authentication. You can see this in the [SSLCARevocationFile](https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslcarevocationfile) or [SSLCARevocationPath](https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslcarevocationpath) documentation (related to `SSLCARevocationCheck`).

 Since this is not something that is generally used when hosting an Angular application, I will close this issue.
